services:
  - type: web
    name: my-php-app
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_DATABASE
        value: oouth_bid
      - key: DB_USERNAME
        value: oouthsal_root
      - key: DB_PASSWORD
        value: Oluwaseyi@7980
      - key: FLUTTERWAVE_SECRET_KEY
        value: FLWSECK_TEST-c2422d3d33df001cb20c77bdf78ffb77-X
      - key: FLUTTERWAVE_PUBLIC_KEY
        value: FLWPUBK_TEST-404f90ae7dfd1b8f6ef70109084bef0f-X
      - key: HOST_MAIL
        value: mail.oouth.com
      - key: USERNAME_MAIL
        value: no-reply@oouth.com
      - key: PASSWORD_MAIL
        value: Masanwo@7980
      - key: FROM_EMAIL
        value: "OOUTH BID"

databases:
  - name: my-mysql-db
    plan: free
    type: mysql
    region: oregon
